import "../styles/styles.scss";
import type { AppProps } from "next/app";
import { CreateRecipeButton } from "../components/CreateRecipeButton/CreateRecipeButton";
import { Header } from "../components/Header/Header";
import Head from "next/head";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Component {...pageProps} />
      <CreateRecipeButton />
    </>
  );
}
export default MyApp;
